### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by sweetNvicious** [dsisco11/SR_Plugin_Loader#39]
i have downloaded your file for the plugin loader and when i scan it it appears that the file has a virus. now, dont tell me my antivirus is wrong because i know for certain that it isnt, please could you fix the virus/remove it so that the loader does not have any viruses attached with it.

**Comment by dylanrenwick** [comment]
In future you should read the FAQ first, it's what it's there for:

> **"My anti-virus thinks the installer is a virus!"**
> 
> Good, it's doing it's job, and while my installer isn't really a virus it does change the code in some game files and that might certainly look like a virus to some AV's.
> This issue isn't unique to my mod installer either, it's an issue with a lot of code changing mods because they alter your game files.
