### ISSUE TITLE
Installer Won't Extract

### ISSUE THREAD

**Issue by ShimmeringPixie** [dsisco11/SR_Plugin_Loader#40]
I'm having an issue where when I look at the installer files through winrar, I can see the SR_PluginLoader_Installer.exe file completely fine. 

![image](https://cloud.githubusercontent.com/assets/23411666/20235188/9e528446-a859-11e6-86a2-7bb379100844.png)

However, when I go to extract it, it won't show up in a regular folder so I can use it. 

![image](https://cloud.githubusercontent.com/assets/23411666/20235191/b7978f1e-a859-11e6-83fa-b73cfdddef10.png)

I've tried extracting the entire Installer.zip file and extracting just the SR_PluginLoader_Installer.exe file and neither work. Can anyone help?

**Comment by dylanrenwick** [comment]
Try temporarily disabling your antivirus, it's been known to detect the installer as a virus due to the way it modifies the game files.
