### ISSUE TITLE
Installer source not found

### ISSUE THREAD

**Issue by dylanrenwick** [dsisco11/SR_Plugin_Loader#42]
According to [this announcement](https://steamcommunity.com/groups/SRMODS#announcements/detail/861702830363721604) on the steam group, the source code for the installer has been released in the repo, however it doesn't seem to be there and the last commit to the repo was the 0.7.5 update on the 20th of may.

Having access to the installer's source would be great right now because, as you may have noticed, the installer's been broken since october and I'd love to finally fix it and continue plugin development. I'm happy to take over maintenance of the plugin loader if you release the installer source, but without it nobody but you can fix these kinds of issues, which is a problem as I assume you are either too busy or no longer interested in maintaining SRPL yourself.

**Comment by dsisco11** [comment]
Sorry about that, yea I kinda shutdown and lost interest because not enough people seemed interested in the project. But if your willing to help manage the project I might eventually get back into it. I sent you a collaboration invite.

**Comment by dylanrenwick** [comment]
Woo! Thanks.

Sorry again for bugging you so much over the past couple of days about it, I'm gunna get to work on fixing it up and getting it working for the latest version. The main reason I was so eager to get the installer source is because, as fun as SR is, it's still pretty content limited, and now with the new science system there's so much cool potential for mods.
