### ISSUE TITLE
Plugin manager window does not work

### ISSUE THREAD

**Issue by dylanrenwick** [dsisco11/SR_Plugin_Loader#45]
Currently on the latest version of the game (v0.4.1) and using the latest build of the dev branch of SRPL, when you click the Plugins button, rather than seeing the functional plugin manager window, all that comes up is this:
![Plugin Manager](http://i.imgur.com/50Zoz9l.jpg)
In this state the mouse is also non-visible and presumed non-functional, and the only way out is to hit Escape, returning to the main menu.

So far by inserting `SLog.Debug` statements at various points, I've discovered that the issue isn't caused by the PluginManager failing to refresh the plugin list or the PluginManager's layout event not being called, however beyond this I don't know enough about how the current UI system works to be able to properly troubleshoot this issue. 

Hopefully @dsisco11 will be able to find the time to look into this at some point.

**Comment by dsisco11** [comment]
I'll look into this bud.
