### ISSUE TITLE
Installation Error?

### ISSUE THREAD

**Issue by Lulzzyth** [dsisco11/SR_Plugin_Loader#46]
When I try running the installer, this comes up in the CMD

> Unhandled Exception: System.TypeInitializationException: The type initializer for 'SR_PluginLoader_Installer.Program' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.
   at SR_PluginLoader_Installer.Program..cctor()
   --- End of inner exception stack trace ---
   at SR_PluginLoader_Installer.Program.Main(String[] args)

**Comment by dylanrenwick** [comment]
The current released installer is for a much older version of Slime Rancher (summer 2016). The rewrite will fix these issues and update the plugin loader to work with current versions of the game.
