### ISSUE TITLE
Installer wont work...

### ISSUE THREAD

**Issue by jjhowe02** [dsisco11/SR_Plugin_Loader#47]
the installer i got from you wont work, heres the things

> INFO: Installing: Sisco's Plugin Loader v0.7.5
> INFO: Checking Assembly...
> INFO: Creating backup: D:\SteamLibrary\steamapps\common\Slime Rancher\SlimeRancher_Data\Managed\Assembly-CSharp.dll
> ERROR: Exception has been thrown by the target of an invocation. Object reference not set to an instance of an object.
> Stack Trace:    at Logging.Logger._OutputLine(LogLevel level, String moduleName, String format, Object[] args) in C:\CODE\GAME_MODS\SR_Plugin_Loader\SR_Plugin_Loader\Logging\Logger.cs:line 121
>    at SR_PluginLoader_Installer.Program.Do_Variable_Changes(ModuleDefinition& dll)
>    at SR_PluginLoader_Installer.Program.Modify_Assembly_DLL(ModuleDefinition dll)
>    at SR_PluginLoader_Installer.Program.Run_Program()
> 
> Outter Stack Trace:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Main(String[] )
> Press ANY key to exit

 and picture: 
![capture3](https://cloud.githubusercontent.com/assets/7963252/24292427/b1a8904a-1063-11e7-8b9f-16271094a60e.PNG)

please help me fix this!

**Comment by jjhowe02** [comment]
GUYS?!?!?!?

**Comment by jjhowe02** [comment]
GUYS, HELP!!!!!!!! I CANT BE LEFT HERE ALONE!!!

**Comment by dylanrenwick** [comment]
The current released installer is for a much older version of Slime Rancher (summer 2016). The rewrite will fix these issues and update the plugin loader to work with current versions of the game.
